/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiStreamMovieRouteImport } from './routes/api/stream/movie'
import { Route as ApiStreamLiveRouteImport } from './routes/api/stream/live'
import { Route as ApiStreamEpisodeRouteImport } from './routes/api/stream/episode'
import { Route as ApiAiOrganizeMediaRouteImport } from './routes/api/ai/organize-media'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStreamMovieRoute = ApiStreamMovieRouteImport.update({
  id: '/api/stream/movie',
  path: '/api/stream/movie',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStreamLiveRoute = ApiStreamLiveRouteImport.update({
  id: '/api/stream/live',
  path: '/api/stream/live',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStreamEpisodeRoute = ApiStreamEpisodeRouteImport.update({
  id: '/api/stream/episode',
  path: '/api/stream/episode',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiOrganizeMediaRoute = ApiAiOrganizeMediaRouteImport.update({
  id: '/api/ai/organize-media',
  path: '/api/ai/organize-media',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/ai/organize-media': typeof ApiAiOrganizeMediaRoute
  '/api/stream/episode': typeof ApiStreamEpisodeRoute
  '/api/stream/live': typeof ApiStreamLiveRoute
  '/api/stream/movie': typeof ApiStreamMovieRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/ai/organize-media': typeof ApiAiOrganizeMediaRoute
  '/api/stream/episode': typeof ApiStreamEpisodeRoute
  '/api/stream/live': typeof ApiStreamLiveRoute
  '/api/stream/movie': typeof ApiStreamMovieRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/ai/organize-media': typeof ApiAiOrganizeMediaRoute
  '/api/stream/episode': typeof ApiStreamEpisodeRoute
  '/api/stream/live': typeof ApiStreamLiveRoute
  '/api/stream/movie': typeof ApiStreamMovieRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/ai/organize-media'
    | '/api/stream/episode'
    | '/api/stream/live'
    | '/api/stream/movie'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/ai/organize-media'
    | '/api/stream/episode'
    | '/api/stream/live'
    | '/api/stream/movie'
  id:
    | '__root__'
    | '/'
    | '/api/ai/organize-media'
    | '/api/stream/episode'
    | '/api/stream/live'
    | '/api/stream/movie'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiAiOrganizeMediaRoute: typeof ApiAiOrganizeMediaRoute
  ApiStreamEpisodeRoute: typeof ApiStreamEpisodeRoute
  ApiStreamLiveRoute: typeof ApiStreamLiveRoute
  ApiStreamMovieRoute: typeof ApiStreamMovieRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stream/movie': {
      id: '/api/stream/movie'
      path: '/api/stream/movie'
      fullPath: '/api/stream/movie'
      preLoaderRoute: typeof ApiStreamMovieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stream/live': {
      id: '/api/stream/live'
      path: '/api/stream/live'
      fullPath: '/api/stream/live'
      preLoaderRoute: typeof ApiStreamLiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stream/episode': {
      id: '/api/stream/episode'
      path: '/api/stream/episode'
      fullPath: '/api/stream/episode'
      preLoaderRoute: typeof ApiStreamEpisodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai/organize-media': {
      id: '/api/ai/organize-media'
      path: '/api/ai/organize-media'
      fullPath: '/api/ai/organize-media'
      preLoaderRoute: typeof ApiAiOrganizeMediaRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiAiOrganizeMediaRoute: ApiAiOrganizeMediaRoute,
  ApiStreamEpisodeRoute: ApiStreamEpisodeRoute,
  ApiStreamLiveRoute: ApiStreamLiveRoute,
  ApiStreamMovieRoute: ApiStreamMovieRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
