/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicHooksEngineDiscoverRouteImport } from './routes/api/public/hooks/engine-discover'
import { Route as ApiPublicHooksEngineEpgRouteImport } from './routes/api/public/hooks/engine-epg'
import { Route as ApiPublicHooksEngineHealthRouteImport } from './routes/api/public/hooks/engine-health'
import { Route as ApiPublicHooksEngineWorkerRouteImport } from './routes/api/public/hooks/engine-worker'
import { Route as ApiPublicV1EpgDotxmlRouteImport } from './routes/api/public/v1/epg[.]xml'
import { Route as ApiPublicV1PlaylistDotm3uRouteImport } from './routes/api/public/v1/playlist[.]m3u'
import { Route as ApiPublicV1StreamsRouteImport } from './routes/api/public/v1/streams'
import { Route as ApiPublicV1StreamIdRouteImport } from './routes/api/public/v1/stream/$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksEngineDiscoverRoute =
  ApiPublicHooksEngineDiscoverRouteImport.update({
    id: '/api/public/hooks/engine-discover',
    path: '/api/public/hooks/engine-discover',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksEngineEpgRoute = ApiPublicHooksEngineEpgRouteImport.update({
  id: '/api/public/hooks/engine-epg',
  path: '/api/public/hooks/engine-epg',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksEngineHealthRoute =
  ApiPublicHooksEngineHealthRouteImport.update({
    id: '/api/public/hooks/engine-health',
    path: '/api/public/hooks/engine-health',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksEngineWorkerRoute =
  ApiPublicHooksEngineWorkerRouteImport.update({
    id: '/api/public/hooks/engine-worker',
    path: '/api/public/hooks/engine-worker',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicV1EpgDotxmlRoute = ApiPublicV1EpgDotxmlRouteImport.update({
  id: '/api/public/v1/epg.xml',
  path: '/api/public/v1/epg.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicV1PlaylistDotm3uRoute =
  ApiPublicV1PlaylistDotm3uRouteImport.update({
    id: '/api/public/v1/playlist.m3u',
    path: '/api/public/v1/playlist.m3u',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicV1StreamsRoute = ApiPublicV1StreamsRouteImport.update({
  id: '/api/public/v1/streams',
  path: '/api/public/v1/streams',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicV1StreamIdRoute = ApiPublicV1StreamIdRouteImport.update({
  id: '/api/public/v1/stream/$id',
  path: '/api/public/v1/stream/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/public/hooks/engine-discover': typeof ApiPublicHooksEngineDiscoverRoute
  '/api/public/hooks/engine-epg': typeof ApiPublicHooksEngineEpgRoute
  '/api/public/hooks/engine-health': typeof ApiPublicHooksEngineHealthRoute
  '/api/public/hooks/engine-worker': typeof ApiPublicHooksEngineWorkerRoute
  '/api/public/v1/epg.xml': typeof ApiPublicV1EpgDotxmlRoute
  '/api/public/v1/playlist.m3u': typeof ApiPublicV1PlaylistDotm3uRoute
  '/api/public/v1/streams': typeof ApiPublicV1StreamsRoute
  '/api/public/v1/stream/$id': typeof ApiPublicV1StreamIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/public/hooks/engine-discover': typeof ApiPublicHooksEngineDiscoverRoute
  '/api/public/hooks/engine-epg': typeof ApiPublicHooksEngineEpgRoute
  '/api/public/hooks/engine-health': typeof ApiPublicHooksEngineHealthRoute
  '/api/public/hooks/engine-worker': typeof ApiPublicHooksEngineWorkerRoute
  '/api/public/v1/epg.xml': typeof ApiPublicV1EpgDotxmlRoute
  '/api/public/v1/playlist.m3u': typeof ApiPublicV1PlaylistDotm3uRoute
  '/api/public/v1/streams': typeof ApiPublicV1StreamsRoute
  '/api/public/v1/stream/$id': typeof ApiPublicV1StreamIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/public/hooks/engine-discover': typeof ApiPublicHooksEngineDiscoverRoute
  '/api/public/hooks/engine-epg': typeof ApiPublicHooksEngineEpgRoute
  '/api/public/hooks/engine-health': typeof ApiPublicHooksEngineHealthRoute
  '/api/public/hooks/engine-worker': typeof ApiPublicHooksEngineWorkerRoute
  '/api/public/v1/epg.xml': typeof ApiPublicV1EpgDotxmlRoute
  '/api/public/v1/playlist.m3u': typeof ApiPublicV1PlaylistDotm3uRoute
  '/api/public/v1/streams': typeof ApiPublicV1StreamsRoute
  '/api/public/v1/stream/$id': typeof ApiPublicV1StreamIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/public/hooks/engine-discover'
    | '/api/public/hooks/engine-epg'
    | '/api/public/hooks/engine-health'
    | '/api/public/hooks/engine-worker'
    | '/api/public/v1/epg.xml'
    | '/api/public/v1/playlist.m3u'
    | '/api/public/v1/streams'
    | '/api/public/v1/stream/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/public/hooks/engine-discover'
    | '/api/public/hooks/engine-epg'
    | '/api/public/hooks/engine-health'
    | '/api/public/hooks/engine-worker'
    | '/api/public/v1/epg.xml'
    | '/api/public/v1/playlist.m3u'
    | '/api/public/v1/streams'
    | '/api/public/v1/stream/$id'
  id:
    | '__root__'
    | '/'
    | '/api/public/hooks/engine-discover'
    | '/api/public/hooks/engine-epg'
    | '/api/public/hooks/engine-health'
    | '/api/public/hooks/engine-worker'
    | '/api/public/v1/epg.xml'
    | '/api/public/v1/playlist.m3u'
    | '/api/public/v1/streams'
    | '/api/public/v1/stream/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiPublicHooksEngineDiscoverRoute: typeof ApiPublicHooksEngineDiscoverRoute
  ApiPublicHooksEngineEpgRoute: typeof ApiPublicHooksEngineEpgRoute
  ApiPublicHooksEngineHealthRoute: typeof ApiPublicHooksEngineHealthRoute
  ApiPublicHooksEngineWorkerRoute: typeof ApiPublicHooksEngineWorkerRoute
  ApiPublicV1EpgDotxmlRoute: typeof ApiPublicV1EpgDotxmlRoute
  ApiPublicV1PlaylistDotm3uRoute: typeof ApiPublicV1PlaylistDotm3uRoute
  ApiPublicV1StreamsRoute: typeof ApiPublicV1StreamsRoute
  ApiPublicV1StreamIdRoute: typeof ApiPublicV1StreamIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/engine-discover': {
      id: '/api/public/hooks/engine-discover'
      path: '/api/public/hooks/engine-discover'
      fullPath: '/api/public/hooks/engine-discover'
      preLoaderRoute: typeof ApiPublicHooksEngineDiscoverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/engine-epg': {
      id: '/api/public/hooks/engine-epg'
      path: '/api/public/hooks/engine-epg'
      fullPath: '/api/public/hooks/engine-epg'
      preLoaderRoute: typeof ApiPublicHooksEngineEpgRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/engine-health': {
      id: '/api/public/hooks/engine-health'
      path: '/api/public/hooks/engine-health'
      fullPath: '/api/public/hooks/engine-health'
      preLoaderRoute: typeof ApiPublicHooksEngineHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/engine-worker': {
      id: '/api/public/hooks/engine-worker'
      path: '/api/public/hooks/engine-worker'
      fullPath: '/api/public/hooks/engine-worker'
      preLoaderRoute: typeof ApiPublicHooksEngineWorkerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/epg.xml': {
      id: '/api/public/v1/epg.xml'
      path: '/api/public/v1/epg.xml'
      fullPath: '/api/public/v1/epg.xml'
      preLoaderRoute: typeof ApiPublicV1EpgDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/playlist.m3u': {
      id: '/api/public/v1/playlist.m3u'
      path: '/api/public/v1/playlist.m3u'
      fullPath: '/api/public/v1/playlist.m3u'
      preLoaderRoute: typeof ApiPublicV1PlaylistDotm3uRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/streams': {
      id: '/api/public/v1/streams'
      path: '/api/public/v1/streams'
      fullPath: '/api/public/v1/streams'
      preLoaderRoute: typeof ApiPublicV1StreamsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/stream/$id': {
      id: '/api/public/v1/stream/$id'
      path: '/api/public/v1/stream/$id'
      fullPath: '/api/public/v1/stream/$id'
      preLoaderRoute: typeof ApiPublicV1StreamIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiPublicHooksEngineDiscoverRoute: ApiPublicHooksEngineDiscoverRoute,
  ApiPublicHooksEngineEpgRoute: ApiPublicHooksEngineEpgRoute,
  ApiPublicHooksEngineHealthRoute: ApiPublicHooksEngineHealthRoute,
  ApiPublicHooksEngineWorkerRoute: ApiPublicHooksEngineWorkerRoute,
  ApiPublicV1EpgDotxmlRoute: ApiPublicV1EpgDotxmlRoute,
  ApiPublicV1PlaylistDotm3uRoute: ApiPublicV1PlaylistDotm3uRoute,
  ApiPublicV1StreamsRoute: ApiPublicV1StreamsRoute,
  ApiPublicV1StreamIdRoute: ApiPublicV1StreamIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
